# Change these first
owner: iqbalpb01
repo: xyz

sites:
  - name: Code Ace
    url: https://codeace.com
    icon: https://i0.wp.com/codeace.com/wp-content/uploads/2019/12/Artboard-1.png
  - name: Wikipedia
    url: https://en.wikipedia.org
    icon: https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

assignees:
  - iqbalpb01    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  favicon: https://i0.wp.com/codeace.com/wp-content/uploads/2019/12/Artboard-1.png
  faviconSvg: https://raw.githubusercontent.com/iqbalpb01/static-assets/main/Artboard-1.svg
  theme: light
  baseUrl: /xyz
  logoUrl: https://i0.wp.com/codeace.com/wp-content/uploads/2019/12/Artboard-1.png
  name: Uptime
  links:
    - rel: stylesheet
      href: https://cdn.beaglesecurity.com/maintenance/status.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/iqbalpb01/xyz
  commitMessages:
  commitAuthorName: "iqbal_bot"
  commitAuthorEmail: "hello@iqbalpb.com"
